## toolboxkit/Container-Begin will be added above

RUN dnf update -y \
    && dnf groupinstall -y basic-desktop-environment \
    && dnf install -y fedora-workstation-repositories \
    && dnf config-manager --set-enabled google-chrome \
    && dnf install -y google-chrome-stable \
    && dnf install -y bash curl file git unzip which xz zip mesa-libGLU clang cmake ninja-build java-17-openjdk-devel.x86_64 \
    && rpm --import https://packages.microsoft.com/keys/microsoft.asc \
    && sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo' \
    && chmod -R o+w /root/ \
    && dnf install -y net-tools code;

COPY --chown=$HOSTUSER_ID:$HOSTUSER_ID ./toolbox-env.sh $TOOLBOX_KIT/
COPY --chown=$HOSTUSER_ID:$HOSTUSER_ID ./toolbox-init.sh $TOOLBOX_KIT/
COPY --chown=$HOSTUSER_ID:$HOSTUSER_ID ./toolbox-boot.sh $TOOLBOX_KIT/
COPY --chown=$HOSTUSER_ID:$HOSTUSER_ID ./toolbox-base-env.sh $TOOLBOX_KIT/bin/env/
RUN mkdir -p $SDK_HOME/

RUN echo $'\n' "# added by toolbox-base "$'\n' \
"source /toolbox/toolbox-env.sh"$'\n' \
"sh /toolbox/toolbox-init.sh"$'\n' \
"# added by toolbox-base end " $'\n' >> /etc/profile.d/toolbox-setenv.sh && cat /etc/profile.d/toolbox-setenv.sh

## toolboxkit/Container-End will be added below
