FROM registry.fedoraproject.org/fedora-toolbox:38 as BASE_IMAGE

ENV TOOLBOX_KIT=/toolbox
ENV SDK_HOME=$TOOLBOX_KIT/sdk

RUN dnf update -y && dnf -y clean all;

COPY ./toolbox-env.sh $TOOLBOX_KIT/bin/
COPY ./toolbox-init.sh $TOOLBOX_KIT/bin/
COPY ./toolbox-boot.sh $TOOLBOX_KIT/bin/
COPY ./toolbox-base-env.sh $TOOLBOX_KIT/bin/env/
RUN mkdir -p $SDK_HOME/

RUN echo $'\n' "# added by toolbox-base "$'\n' \
"source /toolbox/bin/toolbox-env.sh"$'\n' \
"sh /toolbox/bin/toolbox-init.sh"$'\n' \
"# added by toolbox-base end " $'\n' >> /etc/profile.d/toolbox-setenv.sh && cat /etc/profile.d/toolbox-setenv.sh

ENV XDG_CONFIG_HOME=$HOME/.config

## toolboxkit/Container-End will be added below
