FROM registry.fedoraproject.org/fedora-toolbox

RUN sudo dnf groupinstall -y basic-desktop-environment
RUN sudo dnf install -y nodejs

RUN sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
RUN sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
#RUN sudo dnf check-update
RUN sudo dnf install -y code python3-pip
RUN sudo npm install --global yarn
RUN sudo yarn global add ganache-cli
RUN python3 -m pip install --user pipx
RUN python3 -m pipx ensurepath
RUN pipx install eth-brownie
RUN pipx upgrade eth-brownie
RUN brownie --version
RUN echo hello
