FROM registry.fedoraproject.org/fedora-toolbox:34

RUN dnf groupinstall -y basic-desktop-environment
RUN dnf install -y nodejs

RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc
RUN sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
#RUN dnf check-update
RUN dnf install -y code python3-pip python3-devel make gcc
RUN npm install --global yarn
RUN yarn global add ganache-cli
RUN python3 -m pip install --user pipx
RUN python3 -m pipx ensurepath
RUN chmod -R 757 /root/
ENV PATH="/root/.local/bin:${PATH}"
RUN pipx install eth-brownie && pipx upgrade eth-brownie
RUN brownie --version
