## toolboxkit/Container-Begin will be added above

FROM localhost/dev-images-base

RUN mkdir -p $SDK_HOME/idea \
    && curl -o idea.tar.gz "https://download-cdn.jetbrains.com/idea/ideaIC-2023.1.2.tar.gz"  \
    && tar xvzf idea.tar.gz -C $SDK_HOME/idea --strip-components=1 \
    && rm idea.tar.gz 

COPY idea-env.sh $TOOLBOX_KIT/bin/env/

## toolboxkit/Container-End will be added below
