#FROM localhost/flutter-toolbox as flutter
FROM localhost/docker-toolbox as docker-toolbox
FROM localhost/idea-toolbox as idea
FROM localhost/flutter-toolbox as flutter-toolbox
COPY --from=docker-toolbox /toolbox/ /toolbox/
COPY --from=idea /toolbox/ /toolbox/
COPY --from=flutter-toolbox /toolbox/ /toolbox/
