name: idea1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - codecov
  - git-remote-codecommit
variables:
  HOME: /Users/msunkur/dev/toolbox/idea-toolbox-imigo
  TOOLBOX_KIT: $HOME/toolbox
  TOOLBOX_KIT: $TOOLBOX_KIT/sdk
