---
- hosts: all
  gather_facts: True
  become: true
  strategy: free
  tasks:
  - name: Ensure VM is wake up from cloud provioder point of view"
    cron:
      name: "Warm-Up-Disk"
      minute: "*/5"
      job: "dd if=/dev/zero of=/tmp/ddout oflag=direct bs=128k count=5000"
